services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DataFarmX
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dashboard:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      DB_HOST: postgres
      DB_NAME: master
      DB_USER: postgres
      DB_PASSWORD: DataFarmX
    depends_on:
      - postgres

volumes:
  postgres_data:
